<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-12T14:54:22 IST" name="Suite" finished-at="2022-04-12T14:54:34 IST" duration-ms="11209">
    <groups>
    </groups>
    <test started-at="2022-04-12T14:54:22 IST" name="Web Elements" finished-at="2022-04-12T14:54:30 IST" duration-ms="7370">
      <class name="E2EProject.E2EFramework.MainTest">
        <test-method signature="MainPage()[pri:0, instance:E2EProject.E2EFramework.MainTest@1800a575]" started-at="2022-04-12T14:54:22 IST" name="MainPage" finished-at="2022-04-12T14:54:30 IST" duration-ms="7130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MainPage -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:E2EProject.E2EFramework.MainTest@1800a575]" started-at="2022-04-12T14:54:30 IST" name="closeBrowser" finished-at="2022-04-12T14:54:30 IST" duration-ms="158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- E2EProject.E2EFramework.MainTest -->
    </test> <!-- Web Elements -->
    <test started-at="2022-04-12T14:54:30 IST" name="Validate Text" finished-at="2022-04-12T14:54:34 IST" duration-ms="3784">
      <class name="E2EProject.E2EFramework.MainTest">
        <test-method is-config="true" signature="report()[pri:0, instance:E2EProject.E2EFramework.MainTest@1800a575]" started-at="2022-04-12T14:54:34 IST" name="report" finished-at="2022-04-12T14:54:34 IST" duration-ms="638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
      </class> <!-- E2EProject.E2EFramework.MainTest -->
      <class name="E2EProject.E2EFramework.ValidationTest">
        <test-method signature="validateText()[pri:0, instance:E2EProject.E2EFramework.ValidationTest@32c726ee]" started-at="2022-04-12T14:54:30 IST" name="validateText" finished-at="2022-04-12T14:54:33 IST" duration-ms="3621" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [UI Automation] but found [UI Automation Testing]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [UI Automation] but found [UI Automation Testing]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at E2EProject.E2EFramework.ValidationTest.validateText(ValidationTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateText -->
        <test-method is-config="true" signature="close()[pri:0, instance:E2EProject.E2EFramework.ValidationTest@32c726ee]" started-at="2022-04-12T14:54:33 IST" name="close" finished-at="2022-04-12T14:54:34 IST" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="report()[pri:0, instance:E2EProject.E2EFramework.ValidationTest@32c726ee]" started-at="2022-04-12T14:54:34 IST" name="report" finished-at="2022-04-12T14:54:34 IST" duration-ms="147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
      </class> <!-- E2EProject.E2EFramework.ValidationTest -->
    </test> <!-- Validate Text -->
  </suite> <!-- Suite -->
</testng-results>
